apiVersion: api.rcgowda-operator.io/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-scaler
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  # TODO(user): Add fields here
  start: 7 # AM UTC
  end: 11 # AM UTC
  replicas: 2
  deployments:
    - name: nginx
      namespace: default
---
apiVersion: api.rcgowda-operator.io/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-scaler
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  # TODO(user): Add fields here
  start: 12 # AM UTC
  end: 20 # AM UTC
  replicas: 4
  deployments:
    - name: nginx
      namespace: default
